baseURL = "http://franjsco.github.io/"
languageCode = "en-us"
title = "franjsco blog"
theme = "hugo-theme-hello-friend"
publishDir = "docs"
paginate = 5

[params]
  contentTypeName = "posts"
  defaultTheme = "light" # light/dark
  

  showMenuItems = 2
  showReadingTime = false
  toc = false
  # rssFullText = true

[languages]
  [languages.en]
    title = "cd /home/franjsco"
    subtitle = "Another dev blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "cd /home/franjsco"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"